# Generated by Django 4.0.5 on 2022-06-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_calender_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Created Calendar Id'),
        ),
    ]
