# Generated by Django 4.0.5 on 2022-06-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='address1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='address1',
            new_name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
