# Generated by Django 4.0.5 on 2022-06-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
