# Generated by Django 4.0.5 on 2022-06-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Draft',
            new_name='draft',
        ),
    ]
