# Generated by Django 4.0.5 on 2022-06-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_draft_post_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Mental Health', max_length=255),
        ),
    ]
